services:
  - type: web
    name: demo-for-zuplo
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "20"
